# korm-dsl/examples/example-basic/src/main/resources/application.conf

database {
    url = "jdbc:postgresql://localhost:5432/korm_basic"
    url = ${?DB_URL}

    driver = "org.postgresql.Driver"

    user = "postgres"
    user = ${?DB_USER}

    password = "password"
    password = ${?DB_PASSWORD}

    pool {
        maximumPoolSize = 10
        minimumIdle = 2
        connectionTimeout = 30000
        idleTimeout = 600000
        maxLifetime = 1800000
    }
}
